version: '3'

networks:
  web:
    external: true

services:
  bot:
    image: zerodotfive/matrix-webhook
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix-webhook.rule: "Host(`${CHATONS_SERVICE:-matrixwebhook}.${CHATONS_DOMAIN:-localhost}`)"
