---
# my global config
global:
  scrape_interval: 5s 	
  evaluation_interval: 5s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - '/etc/prometheus/alerts.yaml'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 10s
  metrics_path: /metrics
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'alertmanager'
  scrape_interval: 10s
  metrics_path: /metrics
  static_configs:
  - targets: ['localhost:9093']

- job_name: 'blackbox-icmp'
  scrape_interval: 10s
  metrics_path: /probe
  params:
    module: ['icmp']
  static_configs:
    - targets: ['127.0.0.1', '91.200.42.50']
  relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

