name: Publish on Docker Hub

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: zerodotfive/matrix-webhook
      - uses: docker/login-action@v1
        with:
          username: zerodotfive
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
